__author__ = 'itay'
ng_20_ig500 = [u'code', u'sci', u'amplifier', u'Moon', u'spacecraft', u'jimf', u'disk', u'Boyle', u'Dodge', u'120VAC',
               u'X11R5', u'Quadra', u'Honda', u'Host', u'bike', u'Christians', u'lunar', u'Schneider', u'Sternlight',
               u'automotive', u'aurora', u'Sale', u'wiretap', u'Henry', u'GO', u'gnv', u'condition', u'behanna',
               u'Arabs', u'gun', u'Kaldis', u'resistor', u'bikers', u'Leafs', u'team', u'SIMMs', u'Bruins', u'Turkey',
               u'Waco', u'NuBus', u'Appressian', u'Hockey', u'Optilink', u'Percentage', u'port', u'3D', u'VLB',
               u'jaeger', u'Ford', u'TIFF', u'guns', u'3d', u'widget', u'Braves', u'concepts', u'superstition', u'NRA',
               u'baseball', u'Distribution', u'Spencer', u'Jews', u'Devils', u'alaska', u'MS', u'NNTP', u'Clipper',
               u'secure', u'Relations', u'sgi', u'volt', u'Firearms', u'DOS', u'Nntp', u'firearm', u'use', u'would',
               u'arms', u'program', u'Baseball', u'pitching', u'SHO', u'N3JXP', u'Gun', u'riders', u'1993', u'car',
               u'ride', u'clients', u'mwm', u'henry', u'Mustang', u'SE', u'coos', u'Israeli', u'Yamaha', u'chip',
               u'tax', u'foods', u'Bike', u'Lord', u'LC', u'NHL', u'handguns', u'Melkonian', u'Clayton', u'Sandvik',
               u'PGP', u'sin', u'Denning', u'manuals', u'RANCH', u'Cramer', u'Players', u'mac', u'Petaluma', u'X11',
               u'SIMM', u'Apple', u'autos', u'C650', u'DoD', u'algorithms', u'win3', u'Islam', u'Catholic', u'ALink',
               u'consent', u'Weiss', u'Re', u'motorcycle', u'Widget', u'His', u'clh', u'monitor', u'OFFER', u'Soviet',
               u'RAM', u'symptoms', u'window', u'offers', u'Armenian', u'LCIII', u'Bus', u'R5', u'Car', u'Lemieux',
               u'Gordon', u'Murders', u'buphy', u'enterpoop', u'classified', u'crypto', u'egreen', u'Stanley',
               u'Ohanus', u'EISA', u'Sahak', u'ball', u'year', u'Shuttle', u'Riding', u'Serdar', u'ftp', u'driving',
               u'space', u'god', u'dsl', u'BMW', u'kent', u'medicine', u'electronics', u'610', u'cars', u'Jaeger',
               u'Penguins', u'keith', u'card', u'Yankees', u'Clinton', u'launch', u'Apr', u'could', u'privacy',
               u'Hamer', u'Jesus', u'NASA', u'Promise', u'circuit', u'forsale', u'think', u'ATF', u'Duo', u'kaldis',
               u'----------------------------------------------------------------------------', u'Banks', u'Asking',
               u'ISA', u'Diamond', u'Turks', u'atheists', u'digex', u'Frost', u'chastity', u'widgets', u'Wings',
               u'Rushdie', u'geneva', u'floppy', u'season', u'villages', u'PDS', u'1919', u'Skepticism', u'3DO',
               u'Allan', u'dogs', u'patients', u'expo', u'sera', u'cards', u'Xt', u'ifas', u'Pat', u'prb', u'viewer',
               u'God', u'zuma', u'Window', u'solntze', u'tedward', u'sell', u'mountain', u'Christian', u'POV', u'zoo',
               u'Arab', u'animation', u'Graphics', u'detector', u'mit', u'play', u'printer', u'OpenWindows',
               u'SURVIVORS', u'Dodgers', u'CView', u'windows', u'medical', u'disease', u'Earth', u'DIVIDIAN',
               u'playoffs', u'encrypted', u'DETECTORS', u'cdt', u'Rangers', u'biker', u'bikes', u'Kent', u'soldiers',
               u'font', u'Tavares', u'Posting', u'writes', u'crime', u'hockey', u'riding', u'boyle', u'hit',
               u'cryptography', u'strnlght', u'geb', u'hades', u'handgun', u'KSAND', u'runs', u'homosexuals',
               u'motorcycles', u'taxes', u'teams', u'tdawson', u'motherboard', u'sensitivity', u'cica', u'Christianity',
               u'Hendricks', u'wire', u'Towers', u'weapons', u'PC', u'state', u'WARNING', u'Bible', u'FOR', u'VGA',
               u'concentrate', u'key', u'article', u'Forsale', u'Macintosh', u'Mets', u'Chip', u'Kendig', u'pitt',
               u'players', u'Callison', u'games', u'receiver', u'ZX', u'livesey', u'Mozumder', u'Christ', u'GIF',
               u'Turkish', u'color', u'ca', u'BeHanna', u'church', u'Pens', u'COM', u'Macs', u'encryption', u'secret',
               u'SCSI', u'BURNS', u'Morality', u'engine', u'homosexual', u'flight', u'gay', u'fire', u'athos', u'bmp',
               u'graphics', u'driver', u'Motif', u'6E', u'rider', u'Xlib', u'say', u'rutgers', u'Church', u'9615',
               u'motif', u'wlsmith', u'Atheists', u'kmr4', u'callison', u'VRAM', u'orbital', u'helmet', u'Israel',
               u'doctor', u'NSA', u'format', u'wiring', u'firearms', u'shuttle', u'.....(', u'tapped', u'RoyalRoads',
               u'Benedikt', u'psyrobtw', u'oil', u'keys', u'Toyota', u'drives', u'sandvik', u'wpd', u'Cooling',
               u'weapon', u'/#', u'Herringshaw', u'cco', u'client', u'In', u'Sox', u'audio', u'Phillies', u'shameful',
               u'Win3', u'newton', u'BJ', u'voltage', u'amp', u'Scripture', u'jumpers', u'clipper', u'announcement',
               u'transformer', u'Gay', u'drive', u'Taurus', u'caltech', u'board', u'ch981', u'electrical', u'cramer',
               u'lcs', u'government', u'xterm', u'Ceccarelli', u'Harley', u'game', u'()', u'know', u'using',
               u'Countersteering_FAQ', u'apple', u'signal', u'server', u'output', u'security', u'BATF', u'Islanders',
               u'people', u'WINDOWS', u'DES', u')...', u'images', u'intellect', u'HD', u'Rumours', u'AMA', u'moon',
               u'religion', u'Centris', u'Cubs', u'Armenia', u'Keith', u'He', u'patient', u'power', u'Political',
               u'maven', u'br', u'pitchers', u'Livesey', u'Microsoft', u'faith', u'shipping', u'cadre', u'Dumbest',
               u'Cup', u'image', u'Powerbook', u'steveh', u'playoff', u'IDE', u'NL', u'."', u'Mars', u'SALE', u'xpert',
               u'BIOS', u'Alomar', u'optilink', u'NT', u'files', u'offer', u'bus', u'pitcher', u'Detroit', u'escrow',
               u'atheist', u'surrender', u'LED', u'hitter', u'circuits', u'extermination', u'Koresh', u'frequency',
               u'nsmca', u'FBI', u'Jays', u'display', u'rri', u'Toronto', u'Space', u'orbit', u'Armenians', u'sale',
               u'ini', u'file', u'MSG', u'dealer', u'uokmax', u'IIsi', u'polygon', u'Radar', u'drivers', u'treatment',
               u'application', u'Mac', u'interested', u'Israelis', u'Argic', u'Windows', u'PowerBook', u'diet', u'mlee',
               u'FPU', u'486', u'Rosenau', u'Biblical', u'algorithm', u'Win', u'controller', u'atheism', u'Pittsburgh',
               u'nasa', u'directory', u'cpr', u'Gateway']
